### ISSUE TITLE
Unknown column 'm.*'

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/elasticsearch#30]
I just try to set up the beta. When I install the module I get an SQL error. I believe that installation, was succesfull. I think the error comes after trying to load the getContent method. 

`SELECT m.`*`, ml.`name`, ml.`id_lang`
FROM `ps_elasticsearch_meta` m
RIGHT JOIN `ps_elasticsearch_meta_lang` `ml` ON ml.`id_elasticsearch_meta` = m.`id_elasticsearch_meta`
WHERE (ml.`id_lang` IN (1))`

Version: 1.0.3, PHP 7.0.24, MySQL 10.2.8-MariaDB

**Comment by firstred** [comment]
Does the table exist and can you execute this script manually? https://github.com/thirtybees/elasticsearch/blob/master/sql/install.sql

**Comment by firstred** [comment]
Did you grab an early build? The first time we uploaded the module it was packed without the `sql` directory. You might have to redownload it.

**Comment by eschiendorfer** [comment]
The database is there. It's not an early build. The problem are the `

`SELECT m.*, ml.`name`, ml.`id_lang` FROM `ps_elasticsearch_meta` m RIGHT JOIN `ps_elasticsearch_meta_lang` `ml` ON ml.`id_elasticsearch_meta` = m.`id_elasticsearch_meta` WHERE (ml.`id_lang` IN (1))`

This one is working...

**Comment by firstred** [comment]
Ahh, it's an SQL setting I discovered. Using just `m.*` solves it with both configurations.

**Comment by firstred** [comment]
https://github.com/thirtybees/elasticsearch/commit/57064a21f6a755b65996038c0e9df5d27e1d2e4a
