### ISSUE TITLE
Unable to install on TB 1.0.2

### ISSUE THREAD

**Issue by moy2010** [thirtybees/elasticsearch#31]
PHP VERSION: 5.6.2
DATABASE: MYSQL 5.5
THIRTYBEES VERSION: 1.0.2 

DESCRIPTION: 

The module cannot be installed even on a fresh env.

STEPS TO REPRODUCE IT:

Go to modules section and click on "add a new module" in order to upload the module in .zip format.

ERROR THROWN:

[PrestaShop] Fatal error in module file :/home/12887-37436.cloudwaysapps.com/hscxjbvayq/public_html/modules/elasticsearch/elasticsearch.php:
Cannot use isset() on the result of a function call (you can use "null !== func()" instead)

WORKAROUND:

Delete the function getElasticVersion() in elasticsearch.php

**Comment by moy2010** [comment]
I've isolated the issue to this line of code:

elasticsearch.php:529

&& isset($client->cluster()->stats()['nodes']['versions'])

**Comment by firstred** [comment]
Yeah it's a PHP 7.0+ feature I think. That should indeed be changed for 5.6. Note that we are unable to make it work on 5.5 because the Elasticsearch library requires 5.6 or higher.

**Comment by firstred** [comment]
This should fix it: https://github.com/thirtybees/elasticsearch/commit/49da250d73e2a6d7ea677797c458c15c3511d668

**Comment by firstred** [comment]
Just closing these. Feel free to reopen if it still sucks :P
