### ISSUE TITLE
Indexer: Connection cannot be established with ES Node

### ISSUE THREAD

**Issue by moy2010** [thirtybees/elasticsearch#32]
PHP VERSION: 5.6.2
DATABASE: MYSQL 5.5
ES VERSION: 5.4
THIRTYBEES VERSION: 1.0.2

DESCRIPTION:

The module cannot run the indexer function.

STEPS TO REPRODUCE IT:

Set a connection and try click on "Index remaining items".

ERROR THROWN:

Unable to connect with the Elasticsearch server. Has the connection been configured?

PHP ERROR LOG:

PHP Notice:  Undefined index:  in /home/12887-37436.cloudwaysapps.com/hscxjbvayq/public_html/modules/elasticsearch/classes/Indexer.php on line 182

ATTEMPTED WORKAROUND:

Delete the condition check on line 182 in /classes/Indexer.php

WORKAROUND RESULT:

The error is no longer thrown at line 182 in Indexer.php, but the index is not created yet (the same error message is thrown, but there's no error logged in Apache PHP for further debugging).

**Comment by eschiendorfer** [comment]
I have a similair problem. But my error log is empty. I just see an error in console http://example.com/admin/index.php?controller=AdminModules&token=ccd237618500f4c18f42d1a4fe971aa9&configure=elasticsearch&tab_module=front_office_features&module_name=elasticsearch&ajax=1&action=indexRemaining 500 (Internal Server Error)

**Comment by firstred** [comment]
https://github.com/thirtybees/elasticsearch/commit/054ead01c1911a7afebb234dc3bb642ef927379a should do the trick
