### ISSUE TITLE
On php 7.2 /7.3 module can't connect ES because url forming function uses "old" regex expression

### ISSUE THREAD

**Issue by DaoKakao** [thirtybees/elasticsearch#58]
In php 7.2/7.3 rules for regex processing changed slightly (as i found on stackoverflow), so the function splitUrl (module's file elasticsearch.php, startline #1186) produces incorrect result.
Some regex'es in that function contains hyphens. Some of that hyphens in accordance with new rules has to be cloaked with backslash:
line #1191: 
`
$xscheme = '([a-zA-Z][a-zA-Z\d+-.]*)';
`
should be relaced with
`
$xscheme = '([a-zA-Z][a-zA-Z\d+\-.]*)';
`

line #1199
` $xhostName = '([a-zA-Z\d-.%]+)';`

should be relaced with

` $xhostName = '([a-zA-Z\d\-.%]+)';`

**Comment by getdatakick** [comment]
Should be fixed
