### ISSUE TITLE
Indexing stops at 33.33%

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/elasticsearch#60]
For me the indexing proccess doesn't work fully. It stops at 3032/9096 products. What is very strange, since product count on BO shows 3034 products.

I use multistore and have 3 shops installed. It could be related to it...

**Comment by Dh42** [comment]
Looking in elastic, does it always stop on the same product?

**Comment by eschiendorfer** [comment]
How can I find that out? In the logs I dont see an product ids.

**Comment by Dh42** [comment]
Look at your elastic database and see where it stops on indexing. You might install this, https://www.elastic.co/products/kibana
