### ISSUE TITLE
Elasticsearch version: Unknown for 6.4.2

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/elasticsearch#61]
When I follow the offical instructions https://docs.thirtybees.com/native-modules/elastic-search/ I can connect to 5.6.12. But when doing the same for 6.4.2, I always get Elasticsearch version: Unknown. 

Maybe it's because of docker installation, which doesn't add some variables. One of them is ELASTICSEARCH_VERSION.

**Comment by getdatakick** [comment]
Latest version works with ES 5.x, 6.x and 7.x. Please recheck
