### ISSUE TITLE
100 product are taking insane 30 minutes for indexing

### ISSUE THREAD

**Issue by creativeminod** [thirtybees/elasticsearch#62]
- Indexing starts with a normal speed takes 2000 request till 3-4 second
- and then it increases every second
- goes maximum till 100 request for 30 minutes
- I am having 183K products
- It like sea to cross over and reach the full indexing

**Comment by Dh42** [comment]
Your server is loading up, are you using file system caching at the bottom of the performance page?

**Comment by creativeminod** [comment]
Can you please elaborate your point so that I can check it what is the exact point I have to look into

**Comment by Dh42** [comment]
Turn off all caching on the performance settings page in your back office, see if that helps with the indexing speed.

**Comment by creativeminod** [comment]
I already have done that the same thing

![c2](https://user-images.githubusercontent.com/46371669/53391739-563dbe80-39bd-11e9-9bdb-7366c14f0089.PNG)
![c1](https://user-images.githubusercontent.com/46371669/53391740-563dbe80-39bd-11e9-9975-e10a3cdaa178.PNG)

**Comment by creativeminod** [comment]
If I can provide you credentials 
- Can you please check and test it for me using 6.5.4 version 
- Please let me know its very hard to use the extension 
- I am trying from 2 weeks 
- There is some server execution time issue from Elastic Server, something like bandwidth of the request is not working properly.

**Comment by Zengraph** [comment]
You can close this issue, as the new version is really fast to index thousands of products !

**Comment by getdatakick** [comment]
I also confirm that indexing works quite fast. Let's close this issue. If anyone encounter any performance issues, don't hesitate to reopen this
