### ISSUE TITLE
Index speed

### ISSUE THREAD

**Issue by nicdnepr** [thirtybees/elasticsearch#64]
How increase index speed?

**Comment by nicdnepr** [comment]
https://github.com/thirtybees/elasticsearch/blob/master/classes/IndexStatus.php#L218
Looks its part of problems, why need create goods objects list?

**Comment by getdatakick** [comment]
Closing as duplicate of issue #62

**Comment by Zengraph** [comment]
You can close this issue, as the new version is really fast to index thousands of products !
