### ISSUE TITLE
Prestashop v1.7.7.1 not working

### ISSUE THREAD

**Issue by lucmichalski** [thirtybees/elasticsearch#68]
Hi guys,

Hope you are all well !

I tried to install the module on the latest version of Prestashop and it did not work.
I have setup an elastic search v7.7.0 cluster to that.

Any thoughts on how to sort it out ? what could cause the error ?

Thanks for any insights or inputs on that.

Cheers,
Luc Michalski

**Comment by getdatakick** [comment]
This module is for thirtybees, not for prestashop. You could probably make it work on ps16, but definitely not on ps17
